// 3年の復習バンク（書き取り）
//   - 既に習い終えた3年配当漢字。確実に身につく「書き」の土台固め用。
//   - 優先問題(priority)を消化したあと、1日 newPerDay 問ずつ自動で小出しに出る（app.js: buildQueue）。
//   - 形式は他のバンクと共通（prompt/answer/reading/word、空欄は {__}、送りがなは answer に含める）。
window.GRADE3_PROBLEMS = [
  { id: "g3-0001", type: "write", grade: 3, prompt: "{__}い夢を見る", answer: "悪", reading: "わる", word: "悪い" },
  { id: "g3-0002", type: "write", grade: 3, prompt: "ねだんが{__}い", answer: "安", reading: "やす", word: "安い" },
  { id: "g3-0003", type: "write", grade: 3, prompt: "へやが{__}い", answer: "暗", reading: "くら", word: "暗い" },
  { id: "g3-0004", type: "write", grade: 3, prompt: "{__}者にみてもらう", answer: "医", reading: "い", word: "医者" },
  { id: "g3-0005", type: "write", grade: 3, prompt: "やさいを{__}てる", answer: "育", reading: "そだ", word: "育てる" },
  { id: "g3-0006", type: "write", grade: 3, prompt: "水を{__}む", answer: "飲", reading: "の", word: "飲む" },
  { id: "g3-0007", type: "write", grade: 3, prompt: "にもつを{__}ぶ", answer: "運", reading: "はこ", word: "運ぶ" },
  { id: "g3-0008", type: "write", grade: 3, prompt: "プールで{__}ぐ", answer: "泳", reading: "およ", word: "泳ぐ" },
  { id: "g3-0009", type: "write", grade: 3, prompt: "{__}で電車を待つ", answer: "駅", reading: "えき", word: "駅" },
  { id: "g3-0010", type: "write", grade: 3, prompt: "{__}かいスープ", answer: "温", reading: "あたた", word: "温かい" },
  { id: "g3-0011", type: "write", grade: 3, prompt: "まどを{__}ける", answer: "開", reading: "あ", word: "開ける" },
  { id: "g3-0012", type: "write", grade: 3, prompt: "冬は{__}い", answer: "寒", reading: "さむ", word: "寒い" },
  { id: "g3-0013", type: "write", grade: 3, prompt: "ありがたく{__}じる", answer: "感", reading: "かん", word: "感じる" },
  { id: "g3-0014", type: "write", grade: 3, prompt: "{__}字を書く", answer: "漢", reading: "かん", word: "漢字" },
  { id: "g3-0015", type: "write", grade: 3, prompt: "朝早く{__}きる", answer: "起", reading: "お", word: "起きる" },
  { id: "g3-0016", type: "write", grade: 3, prompt: "{__}いで走る", answer: "急", reading: "いそ", word: "急ぐ" },
  { id: "g3-0017", type: "write", grade: 3, prompt: "野{__}をする", answer: "球", reading: "きゅう", word: "野球" },
  { id: "g3-0018", type: "write", grade: 3, prompt: "{__}年の夏", answer: "去", reading: "きょ", word: "去年" },
  { id: "g3-0019", type: "write", grade: 3, prompt: "川に{__}をかける", answer: "橋", reading: "はし", word: "橋" },
  { id: "g3-0020", type: "write", grade: 3, prompt: "じゅ{__}を受ける", answer: "業", reading: "ぎょう", word: "授業" },
  { id: "g3-0021", type: "write", grade: 3, prompt: "すきな{__}を聞く", answer: "曲", reading: "きょく", word: "曲" },
  { id: "g3-0022", type: "write", grade: 3, prompt: "れんしゅうが{__}しい", answer: "苦", reading: "くる", word: "苦しい" },
  { id: "g3-0023", type: "write", grade: 3, prompt: "{__}員を決める", answer: "係", reading: "かかり", word: "係員" },
  { id: "g3-0024", type: "write", grade: 3, prompt: "にもつが{__}い", answer: "軽", reading: "かる", word: "軽い" },
  { id: "g3-0025", type: "write", grade: 3, prompt: "けがで{__}が出る", answer: "血", reading: "ち", word: "血" },
  { id: "g3-0026", type: "write", grade: 3, prompt: "日にちを{__}める", answer: "決", reading: "き", word: "決める" },
  { id: "g3-0027", type: "write", grade: 3, prompt: "{__}究をする", answer: "研", reading: "けん", word: "研究" },
  { id: "g3-0028", type: "write", grade: 3, prompt: "となりの{__}", answer: "県", reading: "けん", word: "県" },
  { id: "g3-0029", type: "write", grade: 3, prompt: "{__}せにくらす", answer: "幸", reading: "しあわ", word: "幸せ" },
  { id: "g3-0030", type: "write", grade: 3, prompt: "船が{__}に着く", answer: "港", reading: "みなと", word: "港" },
  { id: "g3-0031", type: "write", grade: 3, prompt: "{__}事をする", answer: "仕", reading: "し", word: "仕事" },
  { id: "g3-0032", type: "write", grade: 3, prompt: "虫が{__}ぬ", answer: "死", reading: "し", word: "死ぬ" },
  { id: "g3-0033", type: "write", grade: 3, prompt: "道具を{__}う", answer: "使", reading: "つか", word: "使う" },
  { id: "g3-0034", type: "write", grade: 3, prompt: "ゲームを{__}める", answer: "始", reading: "はじ", word: "始める" },
  { id: "g3-0035", type: "write", grade: 3, prompt: "{__}でさし示す", answer: "指", reading: "ゆび", word: "指" },
  { id: "g3-0036", type: "write", grade: 3, prompt: "{__}をみがく", answer: "歯", reading: "は", word: "歯" },
  { id: "g3-0037", type: "write", grade: 3, prompt: "かばんを{__}つ", answer: "持", reading: "も", word: "持つ" },
  { id: "g3-0038", type: "write", grade: 3, prompt: "木の{__}がなる", answer: "実", reading: "み", word: "実" },
  { id: "g3-0039", type: "write", grade: 3, prompt: "しゃ{__}をとる", answer: "写", reading: "しゃ", word: "写真" },
  { id: "g3-0040", type: "write", grade: 3, prompt: "テストを{__}ける", answer: "受", reading: "う", word: "受ける" },
  { id: "g3-0041", type: "write", grade: 3, prompt: "しゅくだいが{__}わる", answer: "終", reading: "お", word: "終わる" },
  { id: "g3-0042", type: "write", grade: 3, prompt: "ピアノを{__}う", answer: "習", reading: "なら", word: "習う" },
  { id: "g3-0043", type: "write", grade: 3, prompt: "切手を{__}める", answer: "集", reading: "あつ", word: "集める" },
  { id: "g3-0044", type: "write", grade: 3, prompt: "町に{__}む", answer: "住", reading: "す", word: "住む" },
  { id: "g3-0045", type: "write", grade: 3, prompt: "にもつが{__}い", answer: "重", reading: "おも", word: "重い" },
  { id: "g3-0046", type: "write", grade: 3, prompt: "{__}題をする", answer: "宿", reading: "しゅく", word: "宿題" },
  { id: "g3-0047", type: "write", grade: 3, prompt: "夏は{__}い", answer: "暑", reading: "あつ", word: "暑い" },
  { id: "g3-0048", type: "write", grade: 3, prompt: "友だちを{__}ける", answer: "助", reading: "たす", word: "助ける" },
  { id: "g3-0049", type: "write", grade: 3, prompt: "火を{__}す", answer: "消", reading: "け", word: "消す" },
  { id: "g3-0050", type: "write", grade: 3, prompt: "しあいに{__}つ", answer: "勝", reading: "か", word: "勝つ" },
  { id: "g3-0051", type: "write", grade: 3, prompt: "バスに{__}る", answer: "乗", reading: "の", word: "乗る" },
  { id: "g3-0052", type: "write", grade: 3, prompt: "木を{__}える", answer: "植", reading: "う", word: "植える" },
  { id: "g3-0053", type: "write", grade: 3, prompt: "川が{__}い", answer: "深", reading: "ふか", word: "深い" },
  { id: "g3-0054", type: "write", grade: 3, prompt: "前へ{__}む", answer: "進", reading: "すす", word: "進む" },
  { id: "g3-0055", type: "write", grade: 3, prompt: "列を{__}える", answer: "整", reading: "ととの", word: "整える" },
  { id: "g3-0056", type: "write", grade: 3, prompt: "手紙を{__}る", answer: "送", reading: "おく", word: "送る" },
  { id: "g3-0057", type: "write", grade: 3, prompt: "足が{__}い", answer: "速", reading: "はや", word: "速い" },
  { id: "g3-0058", type: "write", grade: 3, prompt: "友だちを{__}つ", answer: "待", reading: "ま", word: "待つ" },
  { id: "g3-0059", type: "write", grade: 3, prompt: "ひもが{__}い", answer: "短", reading: "みじか", word: "短い" },
  { id: "g3-0060", type: "write", grade: 3, prompt: "服を{__}る", answer: "着", reading: "き", word: "着る" },
];
