// ============================================================
// ことばクイズ（語彙3択）問題バンク
//   - Tier A: 診断で×/🔺だった6語（priority:true・キャップなしで先に出題）
//   - Tier B〜D: 小4向け抽象語（説明文系・心情/人物系・論理/学習系）
//   - 詳細: reports/kids/読解力_改善プログラム_202607.md の語彙マスターリスト
// ============================================================

window.VOCAB_PROBLEMS = [
  // --- Tier A（優先6語） ---
  { id: "v-0001", word: "性質", reading: "せいしつ", answer: "もともと持っている特徴やたち", distractors: ["見た目のかたち", "値段の高さ"], example: "水の性質を調べる実験をした", priority: true },
  { id: "v-0002", word: "原因", reading: "げんいん", answer: "あることが起こったわけ", distractors: ["起こった後のけっか", "これからの予定"], example: "雨がやんだ原因を考えてみた", priority: true },
  { id: "v-0003", word: "役割", reading: "やくわり", answer: "その人や物が受け持つ仕事", distractors: ["みんなの人気", "かかった時間"], example: "係の役割を決めて発表した", priority: true },
  { id: "v-0004", word: "立場", reading: "たちば", answer: "その人が置かれているじょうきょう", distractors: ["座っている場所", "体の高さ"], example: "相手の立場で考えてみる", priority: true },
  { id: "v-0005", word: "工夫", reading: "くふう", answer: "よりよくするために、あれこれ考えたやり方", distractors: ["だれかのまねをすること", "むずかしくてできないこと"], example: "音が出ないように工夫する", priority: true },
  { id: "v-0006", word: "様子", reading: "ようす", answer: "見たり聞いたりして分かる、そのときのありさま", distractors: ["決まったルール", "次に起こること"], example: "空の様子を見て雨を予想する", priority: true },

  // --- Tier B（説明文系48語） ---
  { id: "v-0007", word: "理由", reading: "りゆう", answer: "そうする、そう考えるためのわけ", distractors: ["起きたけっか", "これからの目標"], example: "休んだ理由をノートに書く" },
  { id: "v-0008", word: "結果", reading: "けっか", answer: "何かをした後に出てくるもの", distractors: ["はじめる前の様子", "そうする理由"], example: "実験の結果をひょうにまとめた" },
  { id: "v-0009", word: "目的", reading: "もくてき", answer: "何かをする、めざしているところ", distractors: ["使った道具", "かかったお金"], example: "健康のために運動する目的がある" },
  { id: "v-0010", word: "方法", reading: "ほうほう", answer: "何かをするためのやり方", distractors: ["やった後の感想", "決まっている時間"], example: "調べる方法をいくつか考えた" },
  { id: "v-0011", word: "特徴", reading: "とくちょう", answer: "他とくらべて目立つところ", distractors: ["全体の大きさ", "作られた場所"], example: "この動物の特徴をノートに書く" },
  { id: "v-0012", word: "変化", reading: "へんか", answer: "前とちがう様子になること", distractors: ["同じ状態が続くこと", "決まりを作ること"], example: "季節によって色が変化する" },
  { id: "v-0013", word: "共通", reading: "きょうつう", answer: "どちらにも当てはまること", distractors: ["まったくちがうこと", "一つしかないこと"], example: "二つの話に共通する点を探す" },
  { id: "v-0014", word: "区別", reading: "くべつ", answer: "ちがいを見分けること", distractors: ["同じものに合わせること", "数を数えること"], example: "ごみの種類を区別してすてる" },
  { id: "v-0015", word: "種類", reading: "しゅるい", answer: "形や性質でグループ分けしたもの", distractors: ["全部の合計", "使い方の説明"], example: "花の種類をずかんで調べる" },
  { id: "v-0016", word: "順序", reading: "じゅんじょ", answer: "ものごとが起こる、または並ぶ順番", distractors: ["起きた場所", "かかった時間の長さ"], example: "作業の順序を紙に書き出す" },
  { id: "v-0017", word: "関係", reading: "かんけい", answer: "二つ以上のものごとのつながり", distractors: ["一つだけの特徴", "決まった答え"], example: "雨と気温の関係を調べる" },
  { id: "v-0018", word: "比較", reading: "ひかく", answer: "二つ以上をくらべること", distractors: ["一つを選ぶこと", "新しく作ること"], example: "去年と今年の記録を比較する" },
  { id: "v-0019", word: "実際", reading: "じっさい", answer: "本当にあったこと、ありのまま", distractors: ["これからの予想", "考えただけのこと"], example: "実際に自分でやってみた" },
  { id: "v-0020", word: "事実", reading: "じじつ", answer: "本当にあったこと", distractors: ["だれかの意見", "これからの予定"], example: "調べて分かった事実を発表する" },
  { id: "v-0021", word: "意見", reading: "いけん", answer: "あることについて自分が思うこと", distractors: ["本当にあったこと", "決まっているルール"], example: "自分の意見を発表する" },
  { id: "v-0022", word: "感想", reading: "かんそう", answer: "見たり聞いたりして感じたこと", distractors: ["調べて分かった事実", "これからの予定"], example: "本を読んだ感想を書く" },
  { id: "v-0023", word: "予想", reading: "よそう", answer: "これから起こることを前もって考えること", distractors: ["もう起きたこと", "決まった答え"], example: "次の展開を予想してみる" },
  { id: "v-0024", word: "想像", reading: "そうぞう", answer: "実際には無いことを頭の中で思いえがくこと", distractors: ["本当にあったこと", "しらべて分かったこと"], example: "未来の町を想像してかく" },
  { id: "v-0025", word: "観察", reading: "かんさつ", answer: "注意して、よく見ること", distractors: ["パッと一回だけ見ること", "音を聞くこと"], example: "植物の育ち方を観察する" },
  { id: "v-0026", word: "実験", reading: "じっけん", answer: "本当かどうかたしかめるためにやってみること", distractors: ["本を読んで調べること", "友だちに聞くこと"], example: "水がこおる実験をした" },
  { id: "v-0027", word: "記録", reading: "きろく", answer: "あとで分かるように書き残すこと", distractors: ["頭の中で考えること", "口で伝えること"], example: "気温の変化を記録する" },
  { id: "v-0028", word: "確認", reading: "かくにん", answer: "まちがいがないか、もう一度たしかめること", distractors: ["新しく考えること", "決めたことを変えること"], example: "答えを確認してから出す" },
  { id: "v-0029", word: "説明", reading: "せつめい", answer: "分かるように話すこと", distractors: ["だまって見ていること", "急いでやること"], example: "やり方をくわしく説明する" },
  { id: "v-0030", word: "報告", reading: "ほうこく", answer: "分かったことや様子を人に伝えること", distractors: ["自分の意見を主張すること", "だれかにたのむこと"], example: "調べた結果を先生に報告する" },
  { id: "v-0031", word: "紹介", reading: "しょうかい", answer: "知らない人や物のことを人に知らせること", distractors: ["こっそりかくすこと", "無理にさせること"], example: "好きな本を友だちに紹介する" },
  { id: "v-0032", word: "内容", reading: "ないよう", answer: "話や本などの中身", distractors: ["本の表紙", "作った人の名前"], example: "物語の内容をまとめる" },
  { id: "v-0033", word: "話題", reading: "わだい", answer: "みんなが話している事がら", distractors: ["決まっているルール", "一人だけの秘密"], example: "クラスで話題になったニュース" },
  { id: "v-0034", word: "中心", reading: "ちゅうしん", answer: "まん中、いちばん大事なところ", distractors: ["いちばんはし", "外に出たところ"], example: "話の中心をまとめる" },
  { id: "v-0035", word: "全体", reading: "ぜんたい", answer: "一つ残らず全部", distractors: ["一部分だけ", "いちばん最初"], example: "クラス全体で協力する" },
  { id: "v-0036", word: "部分", reading: "ぶぶん", answer: "全体の中の一つ一つ", distractors: ["全部まとめたもの", "いちばん最後"], example: "文章の大事な部分に線を引く" },
  { id: "v-0037", word: "材料", reading: "ざいりょう", answer: "何かを作るもとになるもの", distractors: ["できあがったせいひん", "作り方の説明"], example: "料理の材料を買いに行く" },
  { id: "v-0038", word: "必要", reading: "ひつよう", answer: "なくてはこまること", distractors: ["あってもなくてもよいこと", "使い終わったもの"], example: "遠足に必要な物を用意する" },
  { id: "v-0039", word: "便利", reading: "べんり", answer: "都合がよくて役に立つこと", distractors: ["とても高いこと", "使い方が難しいこと"], example: "便利な道具を使って早く終わる" },
  { id: "v-0040", word: "安全", reading: "あんぜん", answer: "あぶなくないこと", distractors: ["楽しいこと", "簡単なこと"], example: "安全に気をつけて工作する" },
  { id: "v-0041", word: "危険", reading: "きけん", answer: "あぶないこと", distractors: ["つまらないこと", "むずかしいこと"], example: "この道は車が多くて危険だ" },
  { id: "v-0042", word: "注意", reading: "ちゅうい", answer: "気をつけること", distractors: ["楽しみにすること", "がまんすること"], example: "手元に注意して切る" },
  { id: "v-0043", word: "効果", reading: "こうか", answer: "やったことによって出てくるよい結果", distractors: ["かかったお金", "使った時間"], example: "練習の効果でうまくなった" },
  { id: "v-0044", word: "影響", reading: "えいきょう", answer: "あることが他のことに変化をあたえること", distractors: ["決まったきまり", "書いてある説明"], example: "天気が体調に影響する" },
  { id: "v-0045", word: "利用", reading: "りよう", answer: "役立つように使うこと", distractors: ["すてること", "しまっておくこと"], example: "図書館を利用して調べる" },
  { id: "v-0046", word: "活用", reading: "かつよう", answer: "じょうずに役立てて使うこと", distractors: ["しまってかくすこと", "こわしてすてること"], example: "休み時間を活用して練習する" },
  { id: "v-0047", word: "代表", reading: "だいひょう", answer: "グループの中で選ばれて全体を表す人や物", distractors: ["いちばん新しいもの", "一番小さいもの"], example: "クラスの代表として発表する" },
  { id: "v-0048", word: "特別", reading: "とくべつ", answer: "ふつうとちがうこと", distractors: ["いつも通りのこと", "決められたルール"], example: "今日は特別なおやつが出た" },
  { id: "v-0049", word: "自然", reading: "しぜん", answer: "人が作ったのではない、もとからあるもの", distractors: ["人が作った建物", "決められたきまり"], example: "自然の中で生き物を観察する" },
  { id: "v-0050", word: "人工", reading: "じんこう", answer: "人の手で作ったもの", distractors: ["もとからあるもの", "だれも使わないもの"], example: "人工の池でこいを育てる" },
  { id: "v-0051", word: "環境", reading: "かんきょう", answer: "まわりの様子やじょうきょう", distractors: ["決まったルール", "自分の意見"], example: "生き物のすみやすい環境を守る" },
  { id: "v-0052", word: "資源", reading: "しげん", answer: "生活に役立てられるもの", distractors: ["使い終わったごみ", "だれかの意見"], example: "水は大切な資源だ" },
  { id: "v-0053", word: "道具", reading: "どうぐ", answer: "何かをするために使うもの", distractors: ["できあがった作品", "作り方の説明"], example: "工作の道具をそろえる" },
  { id: "v-0054", word: "資料", reading: "しりょう", answer: "調べるときに使う本やデータ", distractors: ["自分の感想", "これからの予定"], example: "図書館で資料を集める" },

  // --- Tier C（心情・人物系36語） ---
  { id: "v-0055", word: "性格", reading: "せいかく", answer: "その人らしい心の様子", distractors: ["顔のつくり", "身長や体重"], example: "妹は明るい性格だ" },
  { id: "v-0056", word: "表情", reading: "ひょうじょう", answer: "気持ちが表れた顔の様子", distractors: ["着ている服", "話す速さ"], example: "うれしそうな表情をしている" },
  { id: "v-0057", word: "態度", reading: "たいど", answer: "気持ちが表れた話し方や動き方", distractors: ["顔の形", "好きな食べ物"], example: "しんけんな態度で話を聞く" },
  { id: "v-0058", word: "行動", reading: "こうどう", answer: "実際にすること、動くこと", distractors: ["頭の中で考えたこと", "決まりごと"], example: "けがをした子を助ける行動をした" },
  { id: "v-0059", word: "決心", reading: "けっしん", answer: "こうしようと心を決めること", distractors: ["まよっている様子", "だれかにたのむこと"], example: "毎日練習する決心をした" },
  { id: "v-0060", word: "勇気", reading: "ゆうき", answer: "こわくてもやってみようとする気持ち", distractors: ["びっくりする気持ち", "うれしい気持ち"], example: "発表する勇気を出した" },
  { id: "v-0061", word: "不安", reading: "ふあん", answer: "どうなるか心配な気持ち", distractors: ["楽しみな気持ち", "おこった気持ち"], example: "テストの前は不安になる" },
  { id: "v-0062", word: "安心", reading: "あんしん", answer: "心配がなくなって、ほっとする気持ち", distractors: ["こまっている気持ち", "急いでいる様子"], example: "無事に着いて安心した" },
  { id: "v-0063", word: "緊張", reading: "きんちょう", answer: "どきどきして体がかたくなる気持ち", distractors: ["のんびりした気持ち", "がっかりした気持ち"], example: "発表の前は緊張した" },
  { id: "v-0064", word: "感動", reading: "かんどう", answer: "心が強く動かされること", distractors: ["つまらないと思うこと", "びっくりして困ること"], example: "その話に感動してなみだが出た" },
  { id: "v-0065", word: "後悔", reading: "こうかい", answer: "もっと別のやり方があったと悔やむこと", distractors: ["うまくいって喜ぶこと", "これからの計画"], example: "練習しなかったことを後悔した" },
  { id: "v-0066", word: "満足", reading: "まんぞく", answer: "十分だと思って喜ぶ気持ち", distractors: ["もっとほしいと思う気持ち", "こまっている気持ち"], example: "がんばった結果に満足した" },
  { id: "v-0067", word: "期待", reading: "きたい", answer: "よいことが起こるだろうと待つ気持ち", distractors: ["起こったことへの後悔", "決まったルール"], example: "遠足を期待して待つ" },
  { id: "v-0068", word: "我慢", reading: "がまん", answer: "つらくてもたえること", distractors: ["すぐにあきらめること", "楽しく過ごすこと"], example: "痛くても我慢して歩いた" },
  { id: "v-0069", word: "努力", reading: "どりょく", answer: "目標のためにがんばること", distractors: ["楽をして休むこと", "人にたのむこと"], example: "毎日の努力でうまくなった" },
  { id: "v-0070", word: "協力", reading: "きょうりょく", answer: "力を合わせて一緒にやること", distractors: ["一人だけでやること", "けんかすること"], example: "みんなで協力して片付けた" },
  { id: "v-0071", word: "信頼", reading: "しんらい", answer: "大丈夫だと信じてまかせること", distractors: ["うたがう気持ち", "こわがる気持ち"], example: "友だちを信頼している" },
  { id: "v-0072", word: "尊敬", reading: "そんけい", answer: "すごいと思ってうやまう気持ち", distractors: ["ばかにする気持ち", "こわがる気持ち"], example: "先生を尊敬している" },
  { id: "v-0073", word: "感謝", reading: "かんしゃ", answer: "ありがたいと思う気持ち", distractors: ["もうしわけないと思う気持ち", "うらやましい気持ち"], example: "助けてくれた友だちに感謝する" },
  { id: "v-0074", word: "遠慮", reading: "えんりょ", answer: "気をつかって、ひかえめにすること", distractors: ["自分勝手にすること", "急いでやること"], example: "遠慮せずにおかわりした" },
  { id: "v-0075", word: "素直", reading: "すなお", answer: "ひねくれずにありのままの気持ちを表すこと", distractors: ["うそをつくこと", "こわがること"], example: "素直に「ごめんね」と言った" },
  { id: "v-0076", word: "正直", reading: "しょうじき", answer: "うそをつかず本当のことを言うこと", distractors: ["だまっていること", "自まんすること"], example: "正直に本当のことを話した" },
  { id: "v-0077", word: "親切", reading: "しんせつ", answer: "人のためを思ってやさしくすること", distractors: ["自分のことだけ考えること", "こわがらせること"], example: "道に迷った人に親切にする" },
  { id: "v-0078", word: "冷静", reading: "れいせい", answer: "あわてず落ち着いていること", distractors: ["とてもあわてている様子", "うれしくてはしゃぐ様子"], example: "冷静に考えて行動する" },
  { id: "v-0079", word: "夢中", reading: "むちゅう", answer: "ほかのことを忘れるくらい熱中すること", distractors: ["少しもきょうみがないこと", "つかれてねむること"], example: "本を読むのに夢中になった" },
  { id: "v-0080", word: "必死", reading: "ひっし", answer: "力の限りいっしょうけんめいなこと", distractors: ["のんびりしている様子", "あきらめている様子"], example: "必死に走ってゴールした" },
  { id: "v-0081", word: "真剣", reading: "しんけん", answer: "まじめに、しんけんに取り組むこと", distractors: ["ふざけている様子", "あきていること"], example: "真剣な顔で話を聞く" },
  { id: "v-0082", word: "得意", reading: "とくい", answer: "上手にできて自信があること", distractors: ["うまくできないこと", "きらいなこと"], example: "算数が得意だ" },
  { id: "v-0083", word: "苦手", reading: "にがて", answer: "うまくできなくて自信がないこと", distractors: ["とても上手なこと", "大好きなこと"], example: "泳ぐのが苦手だ" },
  { id: "v-0084", word: "自信", reading: "じしん", answer: "自分ならできると信じる気持ち", distractors: ["うたがう気持ち", "こわがる気持ち"], example: "練習して自信がついた" },
  { id: "v-0085", word: "反省", reading: "はんせい", answer: "自分のよくなかった点を振り返ること", distractors: ["自まんすること", "人をせめること"], example: "忘れ物をしたことを反省した" },
  { id: "v-0086", word: "成長", reading: "せいちょう", answer: "体や心が育って大きくなること", distractors: ["元にもどること", "すぐに終わること"], example: "この一年で大きく成長した" },
  { id: "v-0087", word: "経験", reading: "けいけん", answer: "実際にやってみて身についたこと", distractors: ["本で読んだだけのこと", "これからの予定"], example: "キャンプの経験を話す" },
  { id: "v-0088", word: "失敗", reading: "しっぱい", answer: "うまくいかなかったこと", distractors: ["うまくいったこと", "まだやっていないこと"], example: "実験は失敗に終わった" },
  { id: "v-0089", word: "成功", reading: "せいこう", answer: "うまくいったこと", distractors: ["うまくいかなかったこと", "まだ始めていないこと"], example: "練習の成果で成功した" },
  { id: "v-0090", word: "練習", reading: "れんしゅう", answer: "上手になるためにくり返しやること", distractors: ["一回だけやってみること", "休んでいること"], example: "毎日練習してうまくなる" },

  // --- Tier D（論理・学習系30語） ---
  { id: "v-0091", word: "主張", reading: "しゅちょう", answer: "自分の考えを強く言うこと", distractors: ["だまって聞くこと", "相手に合わせること"], example: "自分の意見を主張する" },
  { id: "v-0092", word: "反対", reading: "はんたい", answer: "ちがう考えを持つこと", distractors: ["同じ考えを持つこと", "何も考えないこと"], example: "その意見に反対する" },
  { id: "v-0093", word: "賛成", reading: "さんせい", answer: "同じ考えだと認めること", distractors: ["ちがう考えを持つこと", "何も言わないこと"], example: "その計画に賛成する" },
  { id: "v-0094", word: "疑問", reading: "ぎもん", answer: "はっきり分からず、たしかめたいこと", distractors: ["もう分かっていること", "決まったルール"], example: "理科の授業で疑問がわいた" },
  { id: "v-0095", word: "解決", reading: "かいけつ", answer: "問題をうまく片付けること", distractors: ["問題が新しく起こること", "だまって我慢すること"], example: "話し合って問題を解決した" },
  { id: "v-0096", word: "課題", reading: "かだい", answer: "やらなければならない問題や仕事", distractors: ["終わったあとの感想", "楽しい思い出"], example: "夏休みの課題に取り組む" },
  { id: "v-0097", word: "問題", reading: "もんだい", answer: "解決しなければならないこまったこと", distractors: ["すでに終わったこと", "自まんできること"], example: "生活の中の問題を見つける" },
  { id: "v-0098", word: "条件", reading: "じょうけん", answer: "何かが成り立つために必要なこと", distractors: ["自分の感想", "できあがった結果"], example: "参加する条件をたしかめる" },
  { id: "v-0099", word: "場合", reading: "ばあい", answer: "あることが起こったとき、じょうきょう", distractors: ["決まった答え", "自分の意見"], example: "雨の場合は中止になる" },
  { id: "v-0100", word: "可能", reading: "かのう", answer: "できること", distractors: ["できないこと", "禁止されていること"], example: "明日までに完成させることは可能だ" },
  { id: "v-0101", word: "準備", reading: "じゅんび", answer: "何かをする前にととのえておくこと", distractors: ["終わったあとの片付け", "見て感想を言うこと"], example: "発表の準備をする" },
  { id: "v-0102", word: "完成", reading: "かんせい", answer: "できあがること", distractors: ["始まったばかりのこと", "こわれること"], example: "工作がついに完成した" },
  { id: "v-0103", word: "発見", reading: "はっけん", answer: "今まで知らなかったことを見つけること", distractors: ["すでに知っていたこと", "だれかに教わったこと"], example: "新しい虫を発見した" },
  { id: "v-0104", word: "発明", reading: "はつめい", answer: "今までなかったものを新しく考えて作ること", distractors: ["すでにあるものを直すこと", "見つけて拾うこと"], example: "べんりな道具を発明する" },
  { id: "v-0105", word: "発表", reading: "はっぴょう", answer: "考えたことや調べたことを人前で話すこと", distractors: ["こっそり伝えること", "だまって聞くこと"], example: "調べたことをクラスで発表する" },
  { id: "v-0106", word: "相談", reading: "そうだん", answer: "どうしたらよいか人に話して意見を聞くこと", distractors: ["一人で決めること", "だまって我慢すること"], example: "先生に相談してみる" },
  { id: "v-0107", word: "約束", reading: "やくそく", answer: "前もって決めておくこと", distractors: ["急に思いついたこと", "終わったあとの感想"], example: "また遊ぶ約束をした" },
  { id: "v-0108", word: "責任", reading: "せきにん", answer: "自分がやらなければならない務め", distractors: ["自分の得意なこと", "楽しい思い出"], example: "係の責任を果たす" },
  { id: "v-0109", word: "知識", reading: "ちしき", answer: "学んで身についた知っていること", distractors: ["これからの予定", "自分の気持ち"], example: "本を読んで知識を増やす" },
  { id: "v-0110", word: "情報", reading: "じょうほう", answer: "何かについて分かることがら", distractors: ["自分の感想", "これからの予定"], example: "天気の情報を調べる" },
  { id: "v-0111", word: "手順", reading: "てじゅん", answer: "物事を進める順番ややり方", distractors: ["終わったあとの結果", "かかった時間"], example: "工作の手順を確かめる" },
  { id: "v-0112", word: "目標", reading: "もくひょう", answer: "目指しているところ", distractors: ["終わったあとの感想", "すでにできたこと"], example: "毎日10分読書する目標を立てる" },
  { id: "v-0113", word: "計画", reading: "けいかく", answer: "前もってやり方や順番を考えておくこと", distractors: ["終わったあとの片付け", "急に思いついたこと"], example: "夏休みの計画を立てる" },
  { id: "v-0114", word: "実行", reading: "じっこう", answer: "計画したことを実際にやること", distractors: ["計画を考えるだけのこと", "やめてしまうこと"], example: "立てた計画を実行する" },
  { id: "v-0115", word: "選択", reading: "せんたく", answer: "いくつかの中から選ぶこと", distractors: ["全部やってみること", "何もしないこと"], example: "好きな方を選択する" },
  { id: "v-0116", word: "集中", reading: "しゅうちゅう", answer: "一つのことに心を向けること", distractors: ["いろいろなことを同時にすること", "ぼんやりすること"], example: "宿題に集中して取り組む" },
  { id: "v-0117", word: "判断", reading: "はんだん", answer: "考えて決めること", distractors: ["だれかにまかせること", "すでに決まっていること"], example: "自分で判断して行動する" },
  { id: "v-0118", word: "整理", reading: "せいり", answer: "きちんと片付けて分かりやすくすること", distractors: ["ちらかすこと", "新しく作ること"], example: "机の上を整理する" },
  { id: "v-0119", word: "感覚", reading: "かんかく", answer: "目や耳などで感じ取る心の働き", distractors: ["決まったルール", "書いてある説明"], example: "手ざわりの感覚で確かめる" },
  { id: "v-0120", word: "共感", reading: "きょうかん", answer: "人の気持ちを自分のことのように感じること", distractors: ["反対の意見を持つこと", "きょうみを持たないこと"], example: "友だちの話に共感した" },
];
